site_name: "Módulo 3.1 – Java"
site_author: "Juan Manuel Piñero Sánchez"
site_url: "https://jmpinero-avante.github.io/ifcd0112avante-material/modulo31-java"

nav:
  - "Fundamentos del lenguaje":
    - "Representación gráfica de clases y objetos en UML": "01-uml.md"
    - "Estructura básica de un proyecto Java con Maven": "02-maven.md"
    - "Introducción a Java y la JVM": "03-jvm.md"
    - "Tipos de datos y operadores": "04-tipos-de-datos.md"
    - "Arrays y matrices": "05-arrays-matrices.md"
    - "Estructuras de control del flujo": "06-estructuras-control.md"

  - "Programación Orientada a Objetos":
    - "Clases y objetos": "07-clases-objetos.md"
    - "Tipos especiales (enums, records, POJO, JavaBean)": "08-tipos-especiales.md"
    - "Clases genéricas": "09-clases-genericas.md"
    - "Utilidades del lenguaje": "10-utilidades-lenguaje.md"
    - "Interfaces en Java": "11-interfaces.md"
    - "Excepciones y manejo de errores": "12-excepciones.md"

  - "Programación avanzada y diseño de software":
    - "Entrada y salida de datos (I/O)": "13-io.md"
    - "Interfaces funcionales y programación lambda": "14-lambdas.md"
    - "Colecciones y Streams": "15-colecciones-streams.md"
    - "JDBC y acceso a bases de datos": "16-jdbc.md"
    - "Arquitectura y Frameworks": "17-arquitectura-frameworks.md"
    - "Hilos y concurrencia": "18-hilos.md"
    - "Patrones de diseño": "19-patrones-diseno.md"


theme:
  name: material
  custom_dir: overrides
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Cambiar a oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Cambiar a claro
  features:
    # Navegación principal
    - navigation.expand       # permite expandir las secciones
    - navigation.sections     # muestra jerarquías en el menú lateral
    - navigation.top          # vuelve arriba con clic en el encabezado
    - navigation.hide         # muestra el botón ☰ para ocultar el menú lateral
    - toc.integrate           # integra el índice dentro del menú lateral

    # Interacción y usabilidad
    - header.autohide         # esconde el header al avanzar hacia abajo
    - content.code.copy       # botón de copiar en bloques de código


extra_css:
  - styles/code-font.css
  - styles/nav-toggle.css
  - styles/diagram.css
  - styles/desktop-drawer.css
  - styles/pdf-buttons.css
  - styles/pdf-academy.css


markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true


plugins:
  - search
  - with-pdf:
      author: "Juan Manuel Piñero Sánchez"
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: pdf/modulo3-java.pdf
      cover_title: "Java"
      cover_subtitle: "IFCD0112 - Programación Orientada a Objetos y Bases de Datos Relacionales"
      copyright: "2025"
      toc_level: 3


extra:
  generators: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmpinero-avante/ifcd0112avante-material
      name: "Repositorio en GitHub"

