site_name: IFCD0112 – Programación Orientada a Objetos
site_url: https://jmpinero-avante.github.io/ifcd0112avante-material/
repo_url: https://github.com/jmpinero-avante/ifcd0112avante-material
repo_name: jmpinero-avante/ifcd0112avante-material

docs_dir: docs   # 👈 Indica dónde están los .md

theme:
  name: material
  custom_dir: overrides
  language: es
  icon:
    logo: material/book
    repo: fontawesome/brands/github
  favicon: assets/avante-logo.png
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - pdf-export:
      verbose: false
      combined: false
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: pdf/

extra_css:
  - styles/pdf-buttons.css

