site_name: IFCD0112 – Programación Orientada a Objetos
site_url: https://jmpinero-avante.github.io/ifcd0112avante-material/
repo_url: https://github.com/jmpinero-avante/ifcd0112avante-material
repo_name: jmpinero-avante/ifcd0112avante-material

theme:
  name: material
  custom_dir: overrides
  language: es
  icon:
    logo: material/book
    repo: fontawesome/brands/github
  favicon: assets/avante-logo.png
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

nav:
  - Inicio: index.md
  - Módulo 1 – Infraestructura: ../docs-site/modulo1-infraestructura/index.md
  - Módulo 2 – Bases de Datos: ../docs-site/modulo2-bases-de-datos/index.md
  - Módulo 3 – Programación en Java: ../docs-site/modulo3-poo-java/index.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - pdf-export:
      verbose: false
      combined: false
      media_type: print

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmpinero-avante
      name: GitHub – jmpinero-avante
    - icon: material/web
      link: https://www.avante.es/
      name: Avante Sevilla
  generator: false

