site_name: "Módulo 2 – Bases de Datos"
site_author: "Juan Manuel Piñero Sánchez"
site_url: "https://jmpinero-avante.github.io/ifcd0112avante-material/modulo2-bases-de-datos"

nav:
  - index.md
  - 01-modelado-y-definicion-de-tablas-en-postgresql.md
  - 01-modelado-y-definicion-de-tablas-en-postgresql.md
  - 02-consultas-en-postgresql.md
  - 03-insercion-uso-y-eliminacion-de-datos.md
  - 04-indices-y-analisis-de-consultas.md
  - 05-programacion-con-funciones-y-procedimientos.md
  - 06-triggers.md
  - 07-casting-de-tipos.md
  - 08-funciones-comunes-en-plpgsql.md
  - 09-formatos-de-fecha-en-postgresql.md
  - 10-instalacion-y-configuracion-de-postgresql-pgadmin-jdbc.md

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  features:
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - with-pdf:
      output_path: pdf/modulo2-bases-de-datos.pdf
      cover_title: "Módulo 2 – Bases de Datos"
      cover_subtitle: "Formación Profesional para el Empleo – IFCD0112"
      author: "Juan Manuel Piñero Sánchez"
      toc_level: 3
      enabled_if_env: ENABLE_PDF_EXPORT

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmpinero-avante/ifcd0112avante-material
      name: "Repositorio en GitHub"

