name: Deploy MkDocs site and PDFs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ENABLE_PDF_EXPORT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MkDocs and dependencies
        working-directory: docs/pages
        run: |
          pip install mkdocs-material mkdocs-pdf-export-plugin pymdown-extensions weasyprint lxml beautifulsoup4

      - name: Build MkDocs site (including PDFs)
        working-directory: docs/pages
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/pages/site
          publish_branch: gh-pages

